#!/usr/bin/env python3
"""KG-aware genomic liftover for GWAS sumstats.

Reads a TSV (optionally .gz) with chromosome + position columns, lifts each
variant from source build to target build via pyliftover, writes a build-
suffixed output TSV, and a sidecar JSON manifest with provenance.

Source / target build can be supplied explicitly OR resolved via the OKG by
passing --okg-dataset-id or --okg-ld-panel-id. When neither path resolves a
build, the script refuses and emits a coverage-gap stub under
okg-coverage-stubs/.

Usage:
    python lift_sumstats.py \\
        --in GWAS/raw/T01.tsv.gz \\
        --source hg38 \\
        --target hg19 \\
        --out GWAS/lifted/T01.hg19.tsv

    python lift_sumstats.py \\
        --in GWAS/raw/T01.tsv.gz \\
        --okg-dataset-id dataset:foo \\
        --okg-ld-panel-id ld_panel:gctb_ukb_ldm13m

Build aliases accepted: hg18/hg19/hg38 and GRCh36/GRCh37/GRCh38 (case-insensitive).
"""

from __future__ import annotations

import argparse
import gzip
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


BUILD_ALIASES = {
    "hg18": "hg18", "grch36": "hg18",
    "hg19": "hg19", "grch37": "hg19", "b37": "hg19", "hg37": "hg19",
    "hg38": "hg38", "grch38": "hg38", "b38": "hg38",
}


def normalize_build(b: Optional[str]) -> Optional[str]:
    if b is None:
        return None
    return BUILD_ALIASES.get(b.lower().strip())


def ensure_pyliftover() -> None:
    """Install pyliftover via uv pip / pip --user if not importable."""
    try:
        import pyliftover  # noqa: F401
        return
    except ImportError:
        pass
    import subprocess
    for cmd in [
        ["uv", "pip", "install", "pyliftover"],
        [sys.executable, "-m", "pip", "install", "--user", "pyliftover"],
    ]:
        try:
            r = subprocess.run(cmd, capture_output=True, text=True)
            if r.returncode == 0:
                print(f"installed pyliftover via: {' '.join(cmd)}",
                      file=sys.stderr)
                return
        except FileNotFoundError:
            continue
    sys.exit("ERROR: could not install pyliftover; try `pip install pyliftover`")


def resolve_build_via_okg(node_id: str, okg_repo: Path) -> Optional[str]:
    """Spawn the OKG MCP server and look up genome_build attr for a node.

    Returns the normalized build string (hg18/hg19/hg38) or None if the
    node doesn't exist or has no genome_build attr.
    """
    import subprocess

    env = os.environ.copy()
    env.setdefault(
        "OKG_DSN",
        "postgres://postgres:okg@localhost:5449/statgen_analysis",
    )
    proc = subprocess.Popen(
        ["uv", "run", "--extra", "mcp", "python",
         "deployments/statgen-analysis/server.py"],
        cwd=str(okg_repo),
        env=env,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        bufsize=1,
    )
    def send(msg):
        proc.stdin.write(json.dumps(msg) + "\n"); proc.stdin.flush()
    def read():
        return json.loads(proc.stdout.readline())
    try:
        send({"jsonrpc": "2.0", "id": 1, "method": "initialize",
              "params": {"protocolVersion": "2024-11-05", "capabilities": {},
                         "clientInfo": {"name": "lift", "version": "0.1"}}})
        read()
        send({"jsonrpc": "2.0", "method": "notifications/initialized"})
        send({"jsonrpc": "2.0", "id": 2, "method": "tools/call",
              "params": {"name": "get_node",
                         "arguments": {"node_id": node_id}}})
        resp = read()
    finally:
        try: proc.stdin.close()
        except Exception: pass
        try: proc.wait(timeout=3)
        except subprocess.TimeoutExpired: proc.terminate()
    sc = resp.get("result", {}).get("structuredContent") or resp.get("result", {})
    attrs = sc.get("attrs") or {}
    return normalize_build(attrs.get("genome_build"))


def emit_coverage_stub(out_dir: Path, dataset_hint: str, reason: str) -> Path:
    slug = dataset_hint.replace(":", "_").replace("/", "_")
    stub_dir = out_dir / "okg-coverage-stubs" / f"add-dataset-{slug}"
    stub_dir.mkdir(parents=True, exist_ok=True)
    p = stub_dir / "proposal.md"
    p.write_text(
        f"""# OKG coverage-gap proposal for dataset `{dataset_hint}`

> Generated by the `liftover` skill because the OKG could not resolve a
> `genome_build` attr for this dataset. Operator should scaffold a paired
> OpenSpec change in the okg repo via
> `cd $OKG_REPO && openspec new change add-dataset-{slug}`
> and add the dataset entry to
> `deployments/<deployment>/methods/methods_literature.yaml` (or the
> appropriate fixture for the dataset's source type) with
> `attrs.genome_build` populated.

## Why
The liftover skill refused this lift because:
  {reason}

## What Changes
- Add a `dataset_metadata` node (or appropriate subtype) with id `{dataset_hint}`
  carrying `attrs.genome_build = "GRCh37"` or `"GRCh38"`, `attrs.provider`,
  `attrs.source_url`, `attrs.release`, `attrs.access_posture`.
"""
    )
    return p


def open_maybe_gz(path: Path, mode: str = "rt"):
    if str(path).endswith(".gz"):
        return gzip.open(path, mode)
    return open(path, mode)


def gwas_catalog_lookup_via_okg(
    accession: str, okg_repo: Path
) -> Optional[dict]:
    """Try to resolve a GCST accession via the OKG (alias search). Returns
    a dict with `node_id`, `genome_build`, `source_url` if found, else None.
    """
    import subprocess

    env = os.environ.copy()
    env.setdefault(
        "OKG_DSN",
        "postgres://postgres:okg@localhost:5449/statgen_analysis",
    )
    proc = subprocess.Popen(
        ["uv", "run", "--extra", "mcp", "python",
         "deployments/statgen-analysis/server.py"],
        cwd=str(okg_repo),
        env=env,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        bufsize=1,
    )
    def send(msg):
        proc.stdin.write(json.dumps(msg) + "\n"); proc.stdin.flush()
    def read():
        return json.loads(proc.stdout.readline())
    try:
        send({"jsonrpc": "2.0", "id": 1, "method": "initialize",
              "params": {"protocolVersion": "2024-11-05", "capabilities": {},
                         "clientInfo": {"name": "lift", "version": "0.1"}}})
        read()
        send({"jsonrpc": "2.0", "method": "notifications/initialized"})
        send({"jsonrpc": "2.0", "id": 2, "method": "tools/call",
              "params": {"name": "search",
                         "arguments": {"query": accession,
                                       "method": "alias",
                                       "limit": 5}}})
        resp = read()
    finally:
        try: proc.stdin.close()
        except Exception: pass
        try: proc.wait(timeout=3)
        except subprocess.TimeoutExpired: proc.terminate()
    sc = resp.get("result", {}).get("structuredContent") or resp.get("result", {})
    for hit in sc.get("results", []):
        if hit.get("subtype") in ("dataset_metadata", "paper"):
            a = hit.get("attrs") or {}
            return {
                "node_id": hit.get("node_id"),
                "genome_build": normalize_build(a.get("genome_build")),
                "source_url": a.get("source_url"),
                "provider": a.get("provider"),
            }
    return None


def gwas_catalog_lookup_via_api(accession: str) -> dict:
    """Fall back to the GWAS Catalog REST API when the OKG doesn't have the
    study. Returns dict with `genome_build`, `harmonised_url`, `ftp_dir`, plus
    raw study metadata. Raises RuntimeError on HTTP failure.
    """
    import urllib.request

    url = f"https://www.ebi.ac.uk/gwas/rest/api/studies/{accession}"
    try:
        with urllib.request.urlopen(url, timeout=30) as resp:
            study = json.loads(resp.read())
    except Exception as e:
        raise RuntimeError(f"GWAS Catalog API lookup failed for "
                            f"{accession}: {e}")
    # The build is in `genotypingTechnologies` or `ancestries` or via
    # `summaryStatisticsFile` / `_embedded`. Most reliably, GWAS Catalog
    # studies use GRCh37 for older sumstats and GRCh38 for newer; the API
    # exposes this via the `summary_statistics_assembly` field of the
    # sumstats record. We pull metadata + best-effort build.
    build = None
    # Newer API: study["summaryStatisticsAssembly"]; older: not exposed.
    for key in ("summaryStatisticsAssembly", "genomeAssembly",
                 "summary_statistics_assembly"):
        if key in study and study[key]:
            build = normalize_build(study[key]); break
    # Construct the FTP path from the study record (the canonical path is
    # /pub/databases/gwas/summary_statistics/<group>/<accession>/).
    # The group is usually <firstAuthor>_<pubmedId>; the API gives us the
    # first author + pubmed via `publicationInfo`.
    ftp_dir = None
    info = study.get("publicationInfo") or {}
    first_author = (info.get("author") or {}).get("fullname")
    pmid = info.get("pubmedId")
    if first_author and pmid:
        # First author surname only, lowercased.
        surname = first_author.split()[-1].lower()
        group = f"{surname}_{pmid}"
        ftp_dir = (f"https://ftp.ebi.ac.uk/pub/databases/gwas/"
                   f"summary_statistics/{group}/{accession}/")
    return {
        "accession": accession,
        "genome_build": build,
        "ftp_dir": ftp_dir,
        "first_author": first_author,
        "pmid": pmid,
        "study_url": url,
    }


def fetch_gwas_catalog_sumstats(
    accession: str,
    cache_dir: Path,
    okg_repo: Path,
) -> dict:
    """Resolve metadata for a GCST accession (OKG-first, GWAS-Catalog-API
    fallback) and download the harmonised sumstats to ``cache_dir``.

    Returns a dict with:
      input_path, source_build, okg_node_ids, fetch_manifest_path
    """
    import hashlib
    import urllib.request

    cache_dir.mkdir(parents=True, exist_ok=True)

    okg_hit = gwas_catalog_lookup_via_okg(accession, okg_repo)
    if okg_hit:
        source_build = okg_hit.get("genome_build")
        download_url = okg_hit.get("source_url")
        okg_node_ids = {"dataset": okg_hit["node_id"]}
        provenance = {"source": "okg", "node_id": okg_hit["node_id"],
                      "okg_attrs": okg_hit}
    else:
        api = gwas_catalog_lookup_via_api(accession)
        source_build = api["genome_build"]
        download_url = None
        okg_node_ids = {}
        provenance = {"source": "gwas_catalog_api", "api_response": api}

    # If we don't have a direct source_url, try the harmonised path under
    # the FTP dir we constructed via the API.
    if download_url is None and provenance["source"] == "gwas_catalog_api":
        api = provenance["api_response"]
        ftp_dir = api.get("ftp_dir")
        if ftp_dir is None:
            raise RuntimeError(
                f"Could not construct GWAS Catalog FTP dir for {accession}; "
                f"OKG didn't have it and the API response was incomplete. "
                f"Pass --in <path> manually."
            )
        # Probe the harmonised dir for a file matching *.h.tsv.gz.
        # We can't list FTP via urllib, so we use the EBI sumstats API:
        # https://www.ebi.ac.uk/gwas/summary-statistics/api/studies/<acc>
        api_url = (f"https://www.ebi.ac.uk/gwas/summary-statistics/api/"
                    f"studies/{accession}")
        try:
            with urllib.request.urlopen(api_url, timeout=30) as resp:
                meta = json.loads(resp.read())
            ss_id = (meta.get("_embedded", {}).get("studies", [{}])[0]
                     or meta)
            # Try a few likely URL fields:
            for k in ("summary_statistics_url", "harmonised_summary_statistics_url"):
                if ss_id.get(k):
                    download_url = ss_id[k]; break
        except Exception:
            pass
        if download_url is None:
            download_url = f"{ftp_dir}harmonised/{accession}.h.tsv.gz"
            provenance["url_inferred"] = True

    if source_build is None:
        raise RuntimeError(
            f"Could not resolve genome_build for {accession} from either OKG "
            f"or the GWAS Catalog REST API. Pass --source explicitly."
        )

    # Download (skip if cached). Verify with a SHA-256 stamp.
    fname = Path(download_url).name
    cached = cache_dir / fname
    if cached.exists() and cached.stat().st_size > 0:
        print(f"using cached: {cached}", file=sys.stderr)
    else:
        print(f"downloading {download_url} -> {cached}", file=sys.stderr)
        try:
            urllib.request.urlretrieve(download_url, cached)
        except Exception as e:
            raise RuntimeError(f"download failed: {e}")
    sha = hashlib.sha256()
    with open(cached, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            sha.update(chunk)
    fetch_manifest = {
        "accession": accession,
        "download_url": download_url,
        "cached_path": str(cached),
        "sha256": sha.hexdigest(),
        "source_build": source_build,
        "okg_node_ids": okg_node_ids,
        "provenance": provenance,
        "captured_at": datetime.now(timezone.utc).isoformat(),
    }
    mpath = cached.with_suffix(cached.suffix + ".fetch.json")
    mpath.write_text(json.dumps(fetch_manifest, indent=2))
    return {
        "input_path": cached,
        "source_build": source_build,
        "okg_node_ids": okg_node_ids,
        "fetch_manifest_path": mpath,
    }


def lift_file(
    in_path: Path,
    out_path: Path,
    source_build: str,
    target_build: str,
    chrom_col: str = "chromosome",
    pos_col: str = "base_pair_location",
    manifest_extras: Optional[dict] = None,
) -> dict:
    """Lift each row's (chrom, pos) and write to out_path. Returns a dict
    with n_input, n_lifted, n_dropped, dropped_reasons, output_path."""
    ensure_pyliftover()
    from pyliftover import LiftOver

    lo = LiftOver(source_build, target_build)
    n_in = n_out = 0
    drops = {"unmapped": 0, "ambiguous": 0, "missing_field": 0}
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open_maybe_gz(in_path, "rt") as fin, open(out_path, "w") as fout:
        header = fin.readline().rstrip("\n").split("\t")
        if chrom_col not in header or pos_col not in header:
            sys.exit(f"ERROR: header missing required cols "
                     f"{chrom_col!r} and/or {pos_col!r}; got {header}")
        ic, ip = header.index(chrom_col), header.index(pos_col)
        fout.write("\t".join(header) + "\n")
        for line in fin:
            n_in += 1
            parts = line.rstrip("\n").split("\t")
            if len(parts) <= max(ic, ip):
                drops["missing_field"] += 1; continue
            chrom_raw = parts[ic]
            try:
                pos = int(parts[ip])
            except ValueError:
                drops["missing_field"] += 1; continue
            chrom = chrom_raw if chrom_raw.startswith("chr") else f"chr{chrom_raw}"
            hits = lo.convert_coordinate(chrom, pos - 1)  # 0-based half-open
            if not hits:
                drops["unmapped"] += 1; continue
            if len(hits) > 1:
                drops["ambiguous"] += 1; continue
            new_chrom, new_pos, _, _ = hits[0]
            new_chrom = new_chrom[3:] if new_chrom.startswith("chr") else new_chrom
            parts[ic] = new_chrom
            parts[ip] = str(new_pos + 1)
            fout.write("\t".join(parts) + "\n")
            n_out += 1
    manifest = {
        "status": "lifted",
        "input": str(in_path),
        "output": str(out_path),
        "source_build": source_build,
        "target_build": target_build,
        "chain_file_source": "pyliftover (UCSC, downloaded on first use)",
        "n_input": n_in,
        "n_lifted": n_out,
        "n_dropped": n_in - n_out,
        "drop_rate": (n_in - n_out) / max(n_in, 1),
        "dropped_reasons": drops,
        "chrom_col": chrom_col,
        "pos_col": pos_col,
        "captured_at": datetime.now(timezone.utc).isoformat(),
    }
    if manifest_extras:
        manifest.update(manifest_extras)
    sidecar = out_path.with_suffix(out_path.suffix + ".lift.json")
    sidecar.write_text(json.dumps(manifest, indent=2))
    return manifest


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--in", dest="input", type=Path, default=None,
                   help="Input sumstats TSV (or .tsv.gz). Mutually exclusive with --gcst.")
    p.add_argument("--gcst", type=str, default=None,
                   help="GWAS Catalog accession (e.g. GCST90704615). Fetches "
                        "the harmonised sumstats from GWAS Catalog into "
                        "--cache-dir before lifting.")
    p.add_argument("--cache-dir", type=Path,
                   default=Path.home() / ".cache" / "gwas-catalog",
                   help="Cache dir for downloaded GWAS Catalog files "
                        "(default: ~/.cache/gwas-catalog)")
    p.add_argument("--out", type=Path, default=None,
                   help="Output path (default: <in>.<target>.tsv)")
    p.add_argument("--source", type=str, default=None,
                   help="Source build (hg18/hg19/hg38 or GRCh36/37/38)")
    p.add_argument("--target", type=str, default=None,
                   help="Target build")
    p.add_argument("--okg-dataset-id", type=str, default=None,
                   help="If --source omitted, resolve via this OKG node id")
    p.add_argument("--okg-ld-panel-id", type=str, default=None,
                   help="If --target omitted, resolve via this OKG ld_panel id")
    p.add_argument("--okg-repo", type=Path,
                   default=Path(os.environ["OKG_REPO"])
                           if os.environ.get("OKG_REPO") else None,
                   help="Path to the okg repo (for MCP-stdio spawn). Honors "
                        "$OKG_REPO env var; required if any --okg-* flag is "
                        "used.")
    p.add_argument("--chrom-col", type=str, default="chromosome")
    p.add_argument("--pos-col", type=str, default="base_pair_location")
    args = p.parse_args()

    if args.input is None and args.gcst is None:
        p.error("either --in <path> or --gcst <accession> is required")
    if args.input is not None and args.gcst is not None:
        p.error("--in and --gcst are mutually exclusive")

    # Any --okg-* / --gcst use requires the OKG repo path.
    needs_okg = (args.okg_dataset_id is not None
                 or args.okg_ld_panel_id is not None
                 or args.gcst is not None)
    if needs_okg and args.okg_repo is None:
        p.error(
            "OKG repo path is required for --okg-dataset-id / "
            "--okg-ld-panel-id / --gcst. Set the $OKG_REPO environment "
            "variable (e.g. `export OKG_REPO=/path/to/your/okg`) or pass "
            "--okg-repo <path>. The OKG must be a clone of an `okg` repo "
            "with a statgen-analysis (or similar) deployment exposing the "
            "MCP server at deployments/<deployment>/server.py."
        )

    okg_node_ids = {}

    # Resolve --gcst into --in + --source by fetching from GWAS Catalog.
    if args.gcst is not None:
        try:
            fetched = fetch_gwas_catalog_sumstats(
                accession=args.gcst,
                cache_dir=args.cache_dir,
                okg_repo=args.okg_repo,
            )
        except RuntimeError as e:
            sys.exit(f"REFUSED: {e}")
        args.input = fetched["input_path"]
        if args.source is None:
            args.source = fetched["source_build"]
        okg_node_ids.update(fetched["okg_node_ids"])
        print(f"fetched {args.gcst} -> {args.input} "
              f"(source_build={args.source})", file=sys.stderr)

    if not args.input.exists():
        p.error(f"input not found: {args.input}")

    target = normalize_build(args.target)
    if target is None and args.okg_ld_panel_id:
        target = resolve_build_via_okg(args.okg_ld_panel_id, args.okg_repo)
        if target is None:
            sys.exit(f"ERROR: OKG node {args.okg_ld_panel_id} has no resolvable "
                     f"genome_build attr")
        okg_node_ids["ld_panel"] = args.okg_ld_panel_id
    if target is None:
        p.error("target build not given; pass --target or --okg-ld-panel-id")

    source = normalize_build(args.source)
    if source is None and args.okg_dataset_id:
        source = resolve_build_via_okg(args.okg_dataset_id, args.okg_repo)
        if source is None:
            stub = emit_coverage_stub(
                args.input.parent.parent,
                args.okg_dataset_id,
                f"OKG node {args.okg_dataset_id!r} has no resolvable "
                f"`genome_build` attr at the latest published generation.",
            )
            sys.exit(f"REFUSED: source build unresolvable for "
                     f"{args.okg_dataset_id}; coverage-gap stub at {stub}")
        okg_node_ids["dataset"] = args.okg_dataset_id
    if source is None:
        stub = emit_coverage_stub(
            args.input.parent.parent,
            args.input.stem,
            "No --source build given and no --okg-dataset-id provided to "
            "resolve via OKG. Refusing to lift unknown-provenance data.",
        )
        sys.exit(f"REFUSED: source build unknown; coverage-gap stub at {stub}")

    if source == target:
        out = args.out or args.input.with_suffix(f".{target}.tsv")
        out.parent.mkdir(parents=True, exist_ok=True)
        if out.exists() and out.resolve() == args.input.resolve():
            print(f"source == target ({source}); input already at target build, "
                  f"no-op", file=sys.stderr)
        else:
            # Copy with build suffix to keep naming uniform.
            with open_maybe_gz(args.input, "rt") as fin, open(out, "w") as fout:
                fout.write(fin.read())
        sidecar = out.with_suffix(out.suffix + ".lift.json")
        sidecar.write_text(json.dumps({
            "status": "no-op",
            "input": str(args.input), "output": str(out),
            "source_build": source, "target_build": target,
            "okg_node_ids": okg_node_ids,
            "captured_at": datetime.now(timezone.utc).isoformat(),
        }, indent=2))
        print(f"no-op (source==target); wrote {out} + sidecar")
        return 0

    out_path = args.out or args.input.with_suffix(f".{target}.tsv")
    manifest = lift_file(
        in_path=args.input,
        out_path=out_path,
        source_build=source,
        target_build=target,
        chrom_col=args.chrom_col, pos_col=args.pos_col,
        manifest_extras={"okg_node_ids": okg_node_ids},
    )
    print(f"lifted {manifest['n_lifted']}/{manifest['n_input']} "
          f"({manifest['drop_rate'] * 100:.2f}% dropped) -> {out_path}")
    if manifest["drop_rate"] > 0.05:
        print("WARNING: drop rate > 5%; verify source build is correct.",
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
